"""initial

Revision ID: d4de02bc9432
Revises: 
Create Date: 2026-01-28 11:41:38.278837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4de02bc9432'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('google_sub', sa.String(), nullable=True),
    sa.Column('gpa_scaling_table', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_sub'), 'users', ['google_sub'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('programs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('cgpa_scaled', sa.Float(), nullable=True),
    sa.Column('cgpa_percentage', sa.Float(), nullable=True),
    sa.Column('gpa_scaling_table', sa.Text(), nullable=True),
    sa.Column('grad_requirement_credits', sa.Float(), nullable=True),
    sa.Column('hide_gpa', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programs_id'), 'programs', ['id'], unique=False)
    op.create_index(op.f('ix_programs_name'), 'programs', ['name'], unique=False)
    op.create_table('semesters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('program_id', sa.String(), nullable=True),
    sa.Column('average_percentage', sa.Float(), nullable=True),
    sa.Column('average_scaled', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semesters_id'), 'semesters', ['id'], unique=False)
    op.create_index(op.f('ix_semesters_name'), 'semesters', ['name'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('semester_id', sa.String(), nullable=True),
    sa.Column('credits', sa.Float(), nullable=True),
    sa.Column('grade_percentage', sa.Float(), nullable=True),
    sa.Column('grade_scaled', sa.Float(), nullable=True),
    sa.Column('include_in_gpa', sa.Boolean(), nullable=True),
    sa.Column('hide_gpa', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.create_index(op.f('ix_courses_name'), 'courses', ['name'], unique=False)
    op.create_table('widgets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('widget_type', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('layout_config', sa.Text(), nullable=True),
    sa.Column('settings', sa.Text(), nullable=True),
    sa.Column('is_removable', sa.Boolean(), nullable=True),
    sa.Column('semester_id', sa.String(), nullable=True),
    sa.Column('course_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_widgets_id'), 'widgets', ['id'], unique=False)
    op.create_index(op.f('ix_widgets_widget_type'), 'widgets', ['widget_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_widgets_widget_type'), table_name='widgets')
    op.drop_index(op.f('ix_widgets_id'), table_name='widgets')
    op.drop_table('widgets')
    op.drop_index(op.f('ix_courses_name'), table_name='courses')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_semesters_name'), table_name='semesters')
    op.drop_index(op.f('ix_semesters_id'), table_name='semesters')
    op.drop_table('semesters')
    op.drop_index(op.f('ix_programs_name'), table_name='programs')
    op.drop_index(op.f('ix_programs_id'), table_name='programs')
    op.drop_table('programs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_google_sub'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
